"""Make archivo_ruta nullable in FacturaBodega

Revision ID: 033db47d1ab2
Revises: db782e405ddf
Create Date: 2026-04-17 15:30:06.271718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033db47d1ab2'
down_revision = 'db782e405ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas_bodega', schema=None) as batch_op:
        batch_op.alter_column('archivo_ruta',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas_bodega', schema=None) as batch_op:
        batch_op.alter_column('archivo_ruta',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
