"""Add creado_por_id to Cliente

Revision ID: 167e5d63ad1b
Revises: 033db47d1ab2
Create Date: 2026-04-20 10:11:56.554260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '167e5d63ad1b'
down_revision = '033db47d1ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_approvals_estado'))

    op.drop_table('price_approvals')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_por_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['creado_por_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creado_por_id')

    op.create_table('price_approvals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendedor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('precio_original', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('precio_solicitado', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('precio_aprobado', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('motivo_rechazo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fecha_solicitud', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_resolucion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('price_approvals_admin_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('price_approvals_product_id_fkey')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('price_approvals_variant_id_fkey')),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], name=op.f('price_approvals_vendedor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('price_approvals_pkey'))
    )
    with op.batch_alter_table('price_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_approvals_estado'), ['estado'], unique=False)

    # ### end Alembic commands ###
