"""Agregar telefono al modelo User

Revision ID: 5389ad944c6a
Revises: b0edae310aa7
Create Date: 2026-03-18 19:54:26.870450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5389ad944c6a'
down_revision = 'b0edae310aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
