"""Update account state system

Revision ID: 6688b6dd36c2
Revises: 167e5d63ad1b
Create Date: 2026-04-20 19:04:11.245786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6688b6dd36c2'
down_revision = '167e5d63ad1b'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Manejo de facturas_bodega: Agregar modalidad y poblar datos existentes
    op.add_column('facturas_bodega', sa.Column('modalidad', sa.String(length=50), nullable=True))
    # Asumimos que si está pagada era de contado, si no era crédito (ajuste aproximado para datos viejos)
    op.execute("UPDATE facturas_bodega SET modalidad = 'contado' WHERE estado = 'Pagado'")
    op.execute("UPDATE facturas_bodega SET modalidad = 'credito' WHERE modalidad IS NULL")
    op.alter_column('facturas_bodega', 'modalidad', nullable=False)

    # 2. Manejo de abonos_bodega: Agregar cliente_id y poblar desde factura_id
    op.add_column('abonos_bodega', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.execute("UPDATE abonos_bodega SET cliente_id = f.cliente_id FROM facturas_bodega f WHERE f.id = abonos_bodega.factura_id")
    
    # Si hubiera abonos huérfanos (raro), podrías necesitar eliminarlos o asignarles un cliente por defecto
    # op.execute("DELETE FROM abonos_bodega WHERE cliente_id IS NULL")
    
    op.alter_column('abonos_bodega', 'cliente_id', nullable=False)
    op.create_foreign_key(None, 'abonos_bodega', 'clientes', ['cliente_id'], ['id'])

    # 3. Hacer factura_id nullable
    op.alter_column('abonos_bodega', 'factura_id', nullable=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas_bodega', schema=None) as batch_op:
        batch_op.drop_column('modalidad')

    with op.batch_alter_table('abonos_bodega', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('factura_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###
