"""Agregar columna precio costo a productos

Revision ID: 880b9bedf861
Revises: 5389ad944c6a
Create Date: 2026-03-18 20:04:35.113686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880b9bedf861'
down_revision = '5389ad944c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_costo', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('precio_costo')

    # ### end Alembic commands ###
