"""Add variant_id to facturas_bodega_detalles

Revision ID: db782e405ddf
Revises: fda4d956d6a5
Create Date: 2026-04-17 14:21:30.020590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db782e405ddf'
down_revision = 'fda4d956d6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warranties')
    op.drop_table('provider_payments')
    op.drop_table('provider_invoices')
    op.drop_table('losses')
    op.drop_table('providers')
    with op.batch_alter_table('facturas_bodega_detalles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product_variants', ['variant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas_bodega_detalles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('variant_id')

    op.create_table('providers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('providers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('empresa', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='providers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('losses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost_at_loss', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('losses_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('losses_pkey'))
    )
    op.create_table('provider_invoices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monto_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('numero_factura', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comprobante', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fecha_factura', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('provider_invoices_provider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_invoices_pkey'))
    )
    op.create_table('provider_payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monto_abonado', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('observacion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fecha_pago', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('provider_payments_provider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_payments_pkey'))
    )
    op.create_table('warranties',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre_manual', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('resolution', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('warranties_product_id_fkey')),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('warranties_sale_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('warranties_pkey'))
    )
    # ### end Alembic commands ###
