"""Added ArqueoCaja model

Revision ID: fd404ea84aba
Revises: b652ac0a8f39
Create Date: 2026-03-23 17:58:01.920396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd404ea84aba'
down_revision = 'b652ac0a8f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arqueo_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_arqueo', sa.Date(), nullable=False),
    sa.Column('base_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gastos_del_dia', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observaciones_gastos', sa.String(length=255), nullable=True),
    sa.Column('total_efectivo_sistema', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_transferencia_sistema', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arqueo_caja')
    # ### end Alembic commands ###
